import tkinter as tk
window=tk.Tk()
window.title("Address Entry Form")
frame1=tk.Frame()
frame1.pack(side=tk.TOP)
fname=tk.Label(master=frame1,text="        First Name:")
fname.pack(side=tk.LEFT)
fent=tk.Entry(master=frame1,width=50)
fent.pack(side=tk.LEFT)
frame2=tk.Frame()
frame2.pack(side=tk.TOP)
lname=tk.Label(master=frame2,text="        Last Name:")
lname.pack(side=tk.LEFT)
lent=tk.Entry(master=frame2,width=50)
lent.pack(side=tk.LEFT)
frame3=tk.Frame()
frame3.pack(side=tk.TOP)
ad=tk.Label(master=frame3,text="   Adress Line 1:")
ad.pack(side=tk.LEFT)
adent=tk.Entry(master=frame3,width=50)
adent.pack(side=tk.LEFT)
frame4=tk.Frame()
frame4.pack(side=tk.TOP)
ad2=tk.Label(master=frame4,text="   Adress Line 2:")
ad2.pack(side=tk.LEFT)
ad2ent=tk.Entry(master=frame4,width=50)
ad2ent.pack(side=tk.LEFT)
frame5=tk.Frame()
frame5.pack(side=tk.TOP)
cn=tk.Label(master=frame5,text="                   city:")
cn.pack(side=tk.LEFT)
cent=tk.Entry(master=frame5,width=50)
cent.pack(side=tk.LEFT)
f6=tk.Frame()
f6.pack(side=tk.TOP)
st=tk.Label(master=f6,text="state/province:")
st.pack(side=tk.LEFT)
stent=tk.Entry(master=f6,width=50)
stent.pack(side=tk.LEFT)
f7=tk.Frame()
f7.pack(side=tk.TOP)
pc=tk.Label(master=f7,text="    postal code:")
pc.pack(side=tk.LEFT)
pcent=tk.Entry(master=f7,width=50)
pcent.pack(side=tk.LEFT)
f8=tk.Frame()
f8.pack(side=tk.TOP)
cont=tk.Label(master=f8,text="          country:")
cont.pack(side=tk.LEFT)
coent=tk.Entry(master=f8,width=50)
coent.pack(side=tk.LEFT)
lframe=tk.Frame(height=10,width=50)
lframe.pack(side=tk.RIGHT)
bun1=tk.Button(master=lframe,text="save",padx=5,pady=5)
bun1.pack(side=tk.RIGHT)
bun2=tk.Button(master=lframe,text="clear",padx=5,pady=5)
bun2.pack(side=tk.RIGHT)
window.mainloop()
